// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           67
// Async Callback:                       1
// Total number of exported functions:  69

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquid_staking
    (
        init => init
        upgrade => upgrade
        getAdmin => get_admin
        getPendingAdmin => get_pending_admin
        setPendingAdmin => set_pending_admin
        acceptAdmin => accept_admin
        isLiquidStaking => is_liquid_staking
        isActive => is_active
        getLsTokenId => get_ls_token_id
        getExchangeRate => get_exchange_rate
        delegate => delegate
        delegatePendingAmount => delegate_pending_amount
        registerLsToken => register_ls_token
        setLsTokenRoles => set_ls_token_roles
        registerUndelegateToken => register_undelegate_token
        setUndelegateTokenRoles => set_undelegate_token_roles
        setDataManager => set_data_manager
        setStateActive => set_state_active
        setStateInactive => set_state_inactive
        whitelistDelegationContract => whitelist_delegation_contract
        blacklistDelegationContract => blacklist_delegation_contract
        changeDelegationContractParams => change_delegation_contract_params
        withdrawReserve => withdraw_reserve
        setTotalFee => set_total_fee
        setDelegationScoreModelParams => set_delegation_score_model_params
        setDelegationSamplingModelParams => set_delegation_sampling_model_params
        clearDelegationSamplingModel => clear_delegation_sampling_model
        deactivateUndelegationAlgorithm => deactivate_undelegation_algorithm
        reactivateUndelegationAlgorithm => reactivate_undelegation_algorithm
        addToMigrationWhitelist => add_to_migration_whitelist
        removeFromMigrationWhitelist => remove_from_migration_whitelist
        removeMeFromMigrationWhitelist => remove_me_from_migration_whitelist
        claimRewardsFrom => claim_rewards_from
        delegateRewards => delegate_rewards
        getState => state
        getLsSupply => ls_token_supply
        getUndelegateTokenId => undelegate_token
        getUndelegateTokenName => undelegate_token_name
        getCashReserve => cash_reserve
        getRewardsReserve => rewards_reserve
        getProtocolReserves => protocol_reserve
        getTotalUndelegated => total_undelegated
        getTotalWithdrawable => total_withdrawable
        getPenaltyById => penalties
        getNextPenaltyId => next_penalty_id
        getDelegationContractsList => delegation_contracts_list
        getMigrationWhitelist => migration_whitelist
        getNumWhitelistedUsers => num_whitelisted_users
        getBlacklistedDelegationContracts => blacklisted_delegation_contracts
        getDelegationContractData => delegation_contract_data
        getUndelegationMode => undelegation_mode
        getLastUndelegateEpoch => last_undelegate_epoch
        getLastContractDataUpdateEpoch => last_contract_data_update_epoch
        getLastClaimRewardsEpoch => last_rewards_claim_epoch
        getUnbondPeriod => unbond_period
        getTotalFee => total_fee
        getDelegationScoreModel => delegation_score_model
        getDelegationSamplingModel => delegation_sampling_model
        getDataManager => data_manager
        getRandomOracle => random_oracle
        unDelegate => undelegate
        unDelegatePendingAmount => undelegate_pending_amount
        withdraw => withdraw
        withdrawFrom => withdraw_from
        penalize => penalize
        withdrawPenalty => withdraw_penalty
        delegatePenalty => delegate_penalty
        withdrawFromPenalty => withdraw_from_penalty
    )
}

multiversx_sc_wasm_adapter::async_callback! { liquid_staking }
