name: CI

on:
  push:
    branches:
      - main
      - devnet
      - develop
  pull_request:
    branches:
      - main
      - devnet
      - develop

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v2.3.5
    with:
      rust-toolchain: nightly-2023-12-11
      vmtools-version: v1.4.60
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
